export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Standy Group LLC",
  headline: "Who are we...?",
  description: "We are the international team of professionals from the traditional multi and mono brand retail and banking sectors, having comprehensive overall experience in sales, marketing and international logistics. In the digitalisation era we have redirected our professional development towards E-commerce, an actively developing growth area with huge potential. We are your WHOLESALE partner. And it MEANS that we are in the same boat and are rowing together with You. We share the natural affection of the partner towards its brand and do all that is necessary for a customer to find Your product at Amazon and other marketplaces, to see the best of it and to purchase it in the most comfortable way. Win- Win is our priority formula in the partnership.We do not promise whole mountains of gold, but we always diligently perform our work.We intend to unlock the potential of each product to the uttermost and to satisfy expectations of our partner from the collaboration to the fullest possible extent.",
  // buttonLable: "Get started",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "Team collaboration",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "services",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Our services",
  headline: "CONTENT MANAGEMENT",
  description: "Product listing – is a principal point of contact of the online customer with the product. Unfortunately, lots of listings are far from ideal and require the professional revision. Our professionals definitely know what the product’s card should be like for a customer to quickly search for it, to find out the brand’s best qualities and to purchase it.  If you have a product doing well and it is still not at Amazon, it is not a problem. We’ll do it for You in line with your marketing rules and existing Amazon regulations. Please, introduce us to Your product and soon afterwards it will be offered for sale at Amazon.",
  // buttonLable: "Learn more",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "Piggy",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "services",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Our services",
  headline: "MAP POLICY",
  description: "We work in accordance with the brand’s price policy, if any. We take remedial actions to those sellers who break the above mentioned policy. We are of the opinion that the rules set by the brand shall equally work for all.",
  imgStart: false,
  img: require("../../images/svg-3.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjFour = {
  id: "services",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Our services",
  headline: "CUSTOMER EXPERIENCE",
  description: "Acting thoroughly in line with the Amazon requirements and applying the cutting edge software we are actively working on increasing the customers’ comments and reviews, being the driver of subsequent sales. Herewith, we know how to get to hear the customer’s opinion. We will let you know about the consumers’ needs. And, in its turn, it will let you be going the extra mile, further developing your product and every once in a while creating a new one. Your brand positioning is getting competitively stronger. The financial results are pleasing. We are working with the high demand product. And the customer acquires the quality product. Everyone is happy.",
  // buttonLable: "Start Now",
  imgStart: true,
  img: require("../../images/svg-4.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjFive = {
  id: "contact",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Our contacts",
  headline: "CONTACT US",
  description: "blablalalaallalalaal",
  imgStart: false,
  img: require("../../images/svg-3.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjSix = {
  id: "contact",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Our contacts",
  headline: "blablalalaallalalaal",
  description: "blablalalaallalalaal",
  // buttonLable: "Start Now",
  imgStart: false,
  img: require("../../images/svg-3.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};
